# Training configuration
task_name_prefix: "<OPEN_VOCABULARY_DETECTION>"
train_batch_size: 16
val_batch_size: 64
num_workers: 0
epochs: 10
learning_rate: 1e-6
model_name: "microsoft/Florence-2-base-ft"
model_revision: "refs/pr/6"
epochs_per_eval: 2
checkpoint_dir: "tool/checkpoints"

# Dataset paths
train_path: "tool/dataset/processed/train_qa_pairs.json"
eval_path: "tool/dataset/processed/test_qa_pairs.json" 