# Training configuration
# task_name_prefix: "<OPEN_VOCABULARY_DETECTION>"
train_batch_size: 8
val_batch_size: 8
num_workers: 0
epochs: 1
learning_rate: 1e-6
model_name: "microsoft/Florence-2-large-ft"
epochs_per_eval: 1
checkpoint_dir: "tool/checkpoints"
max_examples_per_image: 100
# max_iou_examples: 64

# Dataset paths
train_paths: ["tool/dataset/processed/funsd_train_qa_pairs.json", "tool/dataset/processed/xfund_train_qa_pairs.json", "tool/dataset/processed/form-nlu_train_qa_pairs.json"]
eval_path: "tool/dataset/processed/funsd_test_qa_pairs.json"
